import type { NetSuiteFieldDef, NetSuiteRecordType } from '@/types';

const CUSTOMER_FIELDS: NetSuiteFieldDef[] = [
  { fieldId: 'externalId', label: 'External ID', required: false, type: 'text' },
  { fieldId: 'entityId', label: 'Customer ID', required: false, type: 'text' },
  { fieldId: 'companyName', label: 'Company Name', required: true, type: 'text' },
  { fieldId: 'firstName', label: 'First Name', required: false, type: 'text' },
  { fieldId: 'lastName', label: 'Last Name', required: false, type: 'text' },
  { fieldId: 'email', label: 'Email', required: false, type: 'email' },
  { fieldId: 'phone', label: 'Phone', required: false, type: 'phone' },
  { fieldId: 'fax', label: 'Fax', required: false, type: 'phone' },
  { fieldId: 'category', label: 'Category', required: false, type: 'select' },
  { fieldId: 'subsidiary', label: 'Subsidiary', required: true, type: 'select' },
  { fieldId: 'currency', label: 'Currency', required: false, type: 'select' },
  { fieldId: 'terms', label: 'Terms', required: false, type: 'select' },
  { fieldId: 'creditLimit', label: 'Credit Limit', required: false, type: 'currency' },
  { fieldId: 'taxItem', label: 'Tax Item', required: false, type: 'select' },
  { fieldId: 'isPerson', label: 'Is Individual', required: false, type: 'boolean' },
  { fieldId: 'addr1', label: 'Address Line 1', required: false, type: 'text' },
  { fieldId: 'addr2', label: 'Address Line 2', required: false, type: 'text' },
  { fieldId: 'city', label: 'City', required: false, type: 'text' },
  { fieldId: 'state', label: 'State', required: false, type: 'text' },
  { fieldId: 'zip', label: 'Zip Code', required: false, type: 'text' },
  { fieldId: 'country', label: 'Country', required: false, type: 'text' },
  { fieldId: 'url', label: 'Website', required: false, type: 'text' },
  { fieldId: 'comments', label: 'Comments', required: false, type: 'text' },
];

const VENDOR_FIELDS: NetSuiteFieldDef[] = [
  { fieldId: 'externalId', label: 'External ID', required: false, type: 'text' },
  { fieldId: 'entityId', label: 'Vendor ID', required: false, type: 'text' },
  { fieldId: 'companyName', label: 'Company Name', required: true, type: 'text' },
  { fieldId: 'firstName', label: 'First Name', required: false, type: 'text' },
  { fieldId: 'lastName', label: 'Last Name', required: false, type: 'text' },
  { fieldId: 'email', label: 'Email', required: false, type: 'email' },
  { fieldId: 'phone', label: 'Phone', required: false, type: 'phone' },
  { fieldId: 'fax', label: 'Fax', required: false, type: 'phone' },
  { fieldId: 'category', label: 'Category', required: false, type: 'select' },
  { fieldId: 'subsidiary', label: 'Subsidiary', required: true, type: 'select' },
  { fieldId: 'currency', label: 'Currency', required: false, type: 'select' },
  { fieldId: 'terms', label: 'Terms', required: false, type: 'select' },
  { fieldId: 'taxIdNum', label: 'Tax ID', required: false, type: 'text' },
  { fieldId: 'is1099Eligible', label: '1099 Eligible', required: false, type: 'boolean' },
  { fieldId: 'isPerson', label: 'Is Individual', required: false, type: 'boolean' },
  { fieldId: 'addr1', label: 'Address Line 1', required: false, type: 'text' },
  { fieldId: 'addr2', label: 'Address Line 2', required: false, type: 'text' },
  { fieldId: 'city', label: 'City', required: false, type: 'text' },
  { fieldId: 'state', label: 'State', required: false, type: 'text' },
  { fieldId: 'zip', label: 'Zip Code', required: false, type: 'text' },
  { fieldId: 'country', label: 'Country', required: false, type: 'text' },
  { fieldId: 'url', label: 'Website', required: false, type: 'text' },
  { fieldId: 'comments', label: 'Comments', required: false, type: 'text' },
];

const INVENTORY_ITEM_FIELDS: NetSuiteFieldDef[] = [
  { fieldId: 'externalId', label: 'External ID', required: false, type: 'text' },
  { fieldId: 'itemId', label: 'Item Name/Number', required: true, type: 'text' },
  { fieldId: 'displayName', label: 'Display Name', required: false, type: 'text' },
  { fieldId: 'description', label: 'Description', required: false, type: 'text' },
  { fieldId: 'upcCode', label: 'UPC Code', required: false, type: 'text' },
  { fieldId: 'vendorName', label: 'Preferred Vendor', required: false, type: 'text' },
  { fieldId: 'vendorCode', label: 'Vendor Code', required: false, type: 'text' },
  { fieldId: 'cost', label: 'Purchase Price', required: false, type: 'currency' },
  { fieldId: 'salesPrice', label: 'Sales Price', required: false, type: 'currency' },
  { fieldId: 'weight', label: 'Weight', required: false, type: 'number' },
  { fieldId: 'weightUnit', label: 'Weight Unit', required: false, type: 'select' },
  { fieldId: 'unitsType', label: 'Units Type', required: false, type: 'select' },
  { fieldId: 'stockUnit', label: 'Stock Unit', required: false, type: 'select' },
  { fieldId: 'purchaseUnit', label: 'Purchase Unit', required: false, type: 'select' },
  { fieldId: 'saleUnit', label: 'Sale Unit', required: false, type: 'select' },
  { fieldId: 'cogsAccount', label: 'COGS Account', required: false, type: 'select' },
  { fieldId: 'assetAccount', label: 'Asset Account', required: false, type: 'select' },
  { fieldId: 'incomeAccount', label: 'Income Account', required: false, type: 'select' },
  { fieldId: 'taxSchedule', label: 'Tax Schedule', required: false, type: 'select' },
  { fieldId: 'reorderPoint', label: 'Reorder Point', required: false, type: 'number' },
  { fieldId: 'preferredStockLevel', label: 'Preferred Stock Level', required: false, type: 'number' },
  { fieldId: 'location', label: 'Location', required: false, type: 'select' },
  { fieldId: 'subsidiary', label: 'Subsidiary', required: true, type: 'select' },
  { fieldId: 'includeChildren', label: 'Include Children', required: false, type: 'boolean' },
];

const SALES_ORDER_FIELDS: NetSuiteFieldDef[] = [
  { fieldId: 'externalId', label: 'External ID', required: false, type: 'text' },
  { fieldId: 'tranId', label: 'Transaction Number', required: false, type: 'text' },
  { fieldId: 'entity', label: 'Customer', required: true, type: 'text' },
  { fieldId: 'tranDate', label: 'Date', required: true, type: 'date' },
  { fieldId: 'subsidiary', label: 'Subsidiary', required: true, type: 'select' },
  { fieldId: 'department', label: 'Department', required: false, type: 'select' },
  { fieldId: 'class', label: 'Class', required: false, type: 'select' },
  { fieldId: 'location', label: 'Location', required: false, type: 'select' },
  { fieldId: 'currency', label: 'Currency', required: false, type: 'select' },
  { fieldId: 'terms', label: 'Terms', required: false, type: 'select' },
  { fieldId: 'item', label: 'Item', required: true, type: 'text' },
  { fieldId: 'quantity', label: 'Quantity', required: true, type: 'number' },
  { fieldId: 'rate', label: 'Rate', required: false, type: 'currency' },
  { fieldId: 'amount', label: 'Amount', required: false, type: 'currency' },
  { fieldId: 'taxCode', label: 'Tax Code', required: false, type: 'select' },
  { fieldId: 'memo', label: 'Memo', required: false, type: 'text' },
  { fieldId: 'shipMethod', label: 'Ship Method', required: false, type: 'select' },
  { fieldId: 'shipDate', label: 'Ship Date', required: false, type: 'date' },
  { fieldId: 'poNumber', label: 'PO Number', required: false, type: 'text' },
  { fieldId: 'status', label: 'Status', required: false, type: 'select' },
];

const PURCHASE_ORDER_FIELDS: NetSuiteFieldDef[] = [
  { fieldId: 'externalId', label: 'External ID', required: false, type: 'text' },
  { fieldId: 'tranId', label: 'Transaction Number', required: false, type: 'text' },
  { fieldId: 'entity', label: 'Vendor', required: true, type: 'text' },
  { fieldId: 'tranDate', label: 'Date', required: true, type: 'date' },
  { fieldId: 'subsidiary', label: 'Subsidiary', required: true, type: 'select' },
  { fieldId: 'department', label: 'Department', required: false, type: 'select' },
  { fieldId: 'class', label: 'Class', required: false, type: 'select' },
  { fieldId: 'location', label: 'Location', required: false, type: 'select' },
  { fieldId: 'currency', label: 'Currency', required: false, type: 'select' },
  { fieldId: 'terms', label: 'Terms', required: false, type: 'select' },
  { fieldId: 'item', label: 'Item', required: true, type: 'text' },
  { fieldId: 'quantity', label: 'Quantity', required: true, type: 'number' },
  { fieldId: 'rate', label: 'Rate', required: false, type: 'currency' },
  { fieldId: 'amount', label: 'Amount', required: false, type: 'currency' },
  { fieldId: 'taxCode', label: 'Tax Code', required: false, type: 'select' },
  { fieldId: 'memo', label: 'Memo', required: false, type: 'text' },
  { fieldId: 'dueDate', label: 'Due Date', required: false, type: 'date' },
  { fieldId: 'shipTo', label: 'Ship To', required: false, type: 'text' },
  { fieldId: 'approvalStatus', label: 'Approval Status', required: false, type: 'select' },
];

const JOURNAL_ENTRY_FIELDS: NetSuiteFieldDef[] = [
  { fieldId: 'externalId', label: 'External ID', required: false, type: 'text' },
  { fieldId: 'tranId', label: 'Transaction Number', required: false, type: 'text' },
  { fieldId: 'tranDate', label: 'Date', required: true, type: 'date' },
  { fieldId: 'subsidiary', label: 'Subsidiary', required: true, type: 'select' },
  { fieldId: 'currency', label: 'Currency', required: false, type: 'select' },
  { fieldId: 'account', label: 'Account', required: true, type: 'text' },
  { fieldId: 'debit', label: 'Debit', required: false, type: 'currency' },
  { fieldId: 'credit', label: 'Credit', required: false, type: 'currency' },
  { fieldId: 'memo', label: 'Memo', required: false, type: 'text' },
  { fieldId: 'lineMemo', label: 'Line Memo', required: false, type: 'text' },
  { fieldId: 'department', label: 'Department', required: false, type: 'select' },
  { fieldId: 'class', label: 'Class', required: false, type: 'select' },
  { fieldId: 'location', label: 'Location', required: false, type: 'select' },
  { fieldId: 'entity', label: 'Name', required: false, type: 'text' },
  { fieldId: 'approved', label: 'Approved', required: false, type: 'boolean' },
];

const CONTACT_FIELDS: NetSuiteFieldDef[] = [
  { fieldId: 'externalId', label: 'External ID', required: false, type: 'text' },
  { fieldId: 'entityId', label: 'Contact ID', required: false, type: 'text' },
  { fieldId: 'salutation', label: 'Salutation', required: false, type: 'text' },
  { fieldId: 'firstName', label: 'First Name', required: true, type: 'text' },
  { fieldId: 'middleName', label: 'Middle Name', required: false, type: 'text' },
  { fieldId: 'lastName', label: 'Last Name', required: true, type: 'text' },
  { fieldId: 'title', label: 'Job Title', required: false, type: 'text' },
  { fieldId: 'company', label: 'Company', required: false, type: 'text' },
  { fieldId: 'email', label: 'Email', required: false, type: 'email' },
  { fieldId: 'phone', label: 'Phone', required: false, type: 'phone' },
  { fieldId: 'mobilePhone', label: 'Mobile Phone', required: false, type: 'phone' },
  { fieldId: 'fax', label: 'Fax', required: false, type: 'phone' },
  { fieldId: 'subsidiary', label: 'Subsidiary', required: true, type: 'select' },
  { fieldId: 'addr1', label: 'Address Line 1', required: false, type: 'text' },
  { fieldId: 'addr2', label: 'Address Line 2', required: false, type: 'text' },
  { fieldId: 'city', label: 'City', required: false, type: 'text' },
  { fieldId: 'state', label: 'State', required: false, type: 'text' },
  { fieldId: 'zip', label: 'Zip Code', required: false, type: 'text' },
  { fieldId: 'country', label: 'Country', required: false, type: 'text' },
  { fieldId: 'comments', label: 'Comments', required: false, type: 'text' },
];

const EMPLOYEE_FIELDS: NetSuiteFieldDef[] = [
  { fieldId: 'externalId', label: 'External ID', required: false, type: 'text' },
  { fieldId: 'entityId', label: 'Employee ID', required: false, type: 'text' },
  { fieldId: 'salutation', label: 'Salutation', required: false, type: 'text' },
  { fieldId: 'firstName', label: 'First Name', required: true, type: 'text' },
  { fieldId: 'middleName', label: 'Middle Name', required: false, type: 'text' },
  { fieldId: 'lastName', label: 'Last Name', required: true, type: 'text' },
  { fieldId: 'email', label: 'Email', required: false, type: 'email' },
  { fieldId: 'phone', label: 'Phone', required: false, type: 'phone' },
  { fieldId: 'mobilePhone', label: 'Mobile Phone', required: false, type: 'phone' },
  { fieldId: 'title', label: 'Job Title', required: false, type: 'text' },
  { fieldId: 'department', label: 'Department', required: false, type: 'select' },
  { fieldId: 'subsidiary', label: 'Subsidiary', required: true, type: 'select' },
  { fieldId: 'supervisor', label: 'Supervisor', required: false, type: 'text' },
  { fieldId: 'location', label: 'Location', required: false, type: 'select' },
  { fieldId: 'class', label: 'Class', required: false, type: 'select' },
  { fieldId: 'hireDate', label: 'Hire Date', required: false, type: 'date' },
  { fieldId: 'releaseDate', label: 'Release Date', required: false, type: 'date' },
  { fieldId: 'isInactive', label: 'Inactive', required: false, type: 'boolean' },
  { fieldId: 'addr1', label: 'Address Line 1', required: false, type: 'text' },
  { fieldId: 'addr2', label: 'Address Line 2', required: false, type: 'text' },
  { fieldId: 'city', label: 'City', required: false, type: 'text' },
  { fieldId: 'state', label: 'State', required: false, type: 'text' },
  { fieldId: 'zip', label: 'Zip Code', required: false, type: 'text' },
  { fieldId: 'country', label: 'Country', required: false, type: 'text' },
  { fieldId: 'comments', label: 'Comments', required: false, type: 'text' },
];

const FIELD_MAP: Record<NetSuiteRecordType, NetSuiteFieldDef[]> = {
  customer: CUSTOMER_FIELDS,
  vendor: VENDOR_FIELDS,
  inventoryItem: INVENTORY_ITEM_FIELDS,
  salesOrder: SALES_ORDER_FIELDS,
  purchaseOrder: PURCHASE_ORDER_FIELDS,
  journalEntry: JOURNAL_ENTRY_FIELDS,
  contact: CONTACT_FIELDS,
  employee: EMPLOYEE_FIELDS,
};

export function getFieldsForRecordType(recordType: NetSuiteRecordType): NetSuiteFieldDef[] {
  return FIELD_MAP[recordType] || [];
}

export function getRequiredFields(recordType: NetSuiteRecordType): NetSuiteFieldDef[] {
  return getFieldsForRecordType(recordType).filter((f) => f.required);
}
